version: '3.7'

services:
  sqlserver:
    container_name: sqlserver_container
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Developer*123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - ./.docker-data/sqlserver:/var/opt/mssql/data
      
  postgres:
    container_name: postgres_container
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: WorkplaceService
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "Developer*123"
      PGDATA: ./data
    ports:
      - "54320:5432"
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data

  rabbitmq:
      container_name: rabbitmq_container
      image: masstransit/rabbitmq:latest
      ports:
        - "5672:5672"
        - "15672:15672"
