name: local-test
 
on: workflow_dispatch
 
jobs:
  build:
 
    defaults:
      run:
        working-directory: src
 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
 
    steps:
 
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --warnaserror --configuration Release --no-restore
      - name: Core Tests
        working-directory: tests
        run: dotnet test Nox.Core.Tests --no-restore --verbosity normal
      - name: Data Tests
        working-directory: tests
        run: dotnet test Nox.Data.Tests --no-restore --verbosity normal
      - name: Drop And Load Tests
        working-directory: tests
        run: dotnet test Nox.Etl.DropAndLoad.Tests --no-restore --verbosity normal
      - name: Merge New Tests
        working-directory: tests
        run: dotnet test Nox.Etl.MergeNew.Tests --no-restore --verbosity normal
      - name: Generator Tests
        working-directory: tests
        run: dotnet test Nox.Generator.Tests --no-restore --verbosity normal
      - name: Messaging Tests
        working-directory: tests
        run: dotnet test Nox.Messaging.Tests --no-restore --verbosity normal
