name: Publish Schemas

on:
  push:
    branches: [ main ]
    paths:
      - src/Nox.Core/Schemas/**
      - .github/workflows/nox_schema_publish.yaml

jobs:
  schemas-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./src/Nox.Core/Schemas/
          dangerous-clean-slate: true